### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'mixin')

### ISSUE THREAD

**Issue by jsbay** [x-extends/vxe-table-plugin-element#24]
`vue 2.6` + `element-ui 2.15.6` 应该使用哪个版本? 

导入 `vxe-table` 时 正常运行, 导入 `vxe-table-plugin-element` 后报错 

<img width="672" alt="image" src="https://user-images.githubusercontent.com/26533192/156960848-b11e2ed0-3b9b-4e2b-8e07-63434cb28ee4.png">
 
我的 `package.json`
<img width="413" alt="image" src="https://user-images.githubusercontent.com/26533192/156960930-d1a84f94-808b-4260-845c-766994eb251a.png">

```JavaScript
// src/plugins/vxe-table.js
import Vue from 'vue'

import 'xe-utils'
import VXETable from 'vxe-table'
import VXETablePluginElement from 'vxe-table-plugin-element'
import 'vxe-table-plugin-element/dist/style.css'

// 使用 VXETable
Vue.use(VXETable)
// 使用 VXETablePluginElement
Vue.use(VXETablePluginElement)
```

我应该下载哪个版本的 `vxe-table-plugin-element`，翻阅文档后，暂未找到相关说明,谢谢

**Comment by wuwen635028360** [comment]
一样的问题，请问解决了吗

**Comment by DreamFJ** [comment]
请问后来解决了么，怎么解决的呀

**Comment by jsbay** [comment]
我这边是最后发现不用这个插件也没问题

**Comment by DreamFJ** [comment]
> 我这边是最后发现不用这个插件也没问题

不用的话使用element-ui的下拉框或者时间选择器时无法选中
